import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchTop12CryptoData, fetchSearchCryptoData } from "./cryptoAPI";

const initialState = {
  data: [],
  filterData: [],
};

export const cryptoData = createAsyncThunk(
  "counter/fetchCryptoData",
  async () => {
    const response = await fetchTop12CryptoData();
    return response.data;
  }
);
export const cryptoSearchData = createAsyncThunk(
  "counter/fetchCryptoSearchData",
  async (name) => {
    const response = await fetchSearchCryptoData(name);
    return response.data;
  }
);
export const counterSlice = createSlice({
  name: "crypto-data",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // increment: (state) => {
    //   // Redux Toolkit allows us to write "mutating" logic in reducers. It
    //   // doesn't actually mutate the state because it uses the Immer library,
    //   // which detects changes to a "draft state" and produces a brand new
    //   // immutable state based off those changes
    //   state.value += 1;
    // },
    // decrement: (state) => {
    //   state.value -= 1;
    // },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    filterData: (state, action) => {
      state.filterData = [action.payload];
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(cryptoData.pending, (state) => {
        state.status = "loading";
      })
      .addCase(cryptoData.fulfilled, (state, action) => {
        state.status = "idle";
        state.data = action.payload;
      })
      .addCase(cryptoSearchData.pending, (state) => {
        state.status = "loading";
      })
      .addCase(cryptoSearchData.fulfilled, (state, action) => {
        state.status = "idle";
        state.filterData = action.payload;
      });
  },
});
export const { filterData } = counterSlice.actions;

export const selectCryptoData = (state) => state.counter.data.data;
export const selectStatus = (state) => state.counter.status;
export const selectFilterData = (state) => state.counter.filterData;

export const filteredData = (name) => async (dispatch, getState) => {
  const data = await dispatch(cryptoSearchData(name));
  if (data.payload) {
    dispatch(filterData(data?.payload?.data?.find((l) => l.baseId === name)));
  }
};

export default counterSlice.reducer;
